### PR TITLE
Replace hardcoded database credentials with env vars

### PR DESCRIPTION
**Pull request by nazeefahmadmeer**
fixes issue #93 

Why?
- App is failing to setup/run locally because of the invalid credentials

How?
- Use the env vars defined in .env file instead

### CODE REVIEW

**Comment by wassson** [comment]
Yes! This is a great catch. Thanks for putting the PR up

**Review by wassson — APPROVED** [review]

**Comment by wassson** [comment]
Going to fix the CI failure stuff when I get back to a computer. We'll hold off on merging this until then.

**Comment by nazeefahmadmeer** [comment]
Thanks @wassson, looks to be missing `DB_HOST` env var for the ci workflow, I just pushed to add it. Looks like I don't have permissions to run the workflow, will leave it with you, but let me know if any further changes are required. (alternatively can add a fallback to the DB_HOST in case its not defined, but seems like this is the only place where its not defined, so let's see if CI goes green now)

**Comment by wassson** [comment]
Done 👊 Thanks @nazeefahmadmeer !

**Comment by wassson** [comment]
Done 👊 Thanks @nazeefahmadmeer !

**Pull request merged**
